class AppStrings {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'settings': 'Settings',
      'language': 'Language / भाषा',
      'get_in_touch': 'Get in Touch',
      'contact_desc': 'If you have any questions, feedback, or concerns about our news content, please feel free to reach out to us using the contact information below.',
      'website': 'Website',
      'email': 'Email',
      'follow_us': 'Follow Us',
      'home': 'Home',
      'bookmarks': 'Bookmarks',
      'all': 'All',
      'no_news': 'No news available.',
      'unable_to_load': 'Unable to load news: ',
      'try_again': 'Try Again',
      'search_hint': 'Search news...',
      'enter_search': 'Enter a search term',
      'no_results': 'No results found.',
      'error': 'Error: ',
      'videos': 'VIDEOS',
      'no_videos': 'No videos available.',
      'no_news_category': 'No news available in this category.',
      'saved': 'SAVED',
      'no_saved': 'No saved articles.',
      'check_out': 'Check out this article: ',
      'unknown': 'Unknown',
      'explore': 'EXPLORE',
    },
    'hi': {
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'get_in_touch': 'संपर्क करें',
      'contact_desc': 'यदि आपके पास हमारे समाचारों के बारे में कोई प्रश्न, प्रतिक्रिया या चिंता है, तो कृपया नीचे दी गई संपर्क जानकारी का उपयोग करके हमसे संपर्क करें।',
      'website': 'वेबसाइट',
      'email': 'ईमेल',
      'follow_us': 'हमें फॉलो करें',
      'home': 'होम',
      'bookmarks': 'बुकमार्क',
      'all': 'सभी',
      'no_news': 'कोई समाचार उपलब्ध नहीं है।',
      'unable_to_load': 'समाचार लोड करने में असमर्थ: ',
      'try_again': 'पुनः प्रयास करें',
      'search_hint': 'समाचार खोजें...',
      'enter_search': 'खोजने के लिए शब्द दर्ज करें',
      'no_results': 'कोई परिणाम नहीं मिला।',
      'error': 'त्रुटि: ',
      'videos': 'वीडियो',
      'no_videos': 'कोई वीडियो उपलब्ध नहीं है।',
      'no_news_category': 'इस श्रेणी में कोई समाचार उपलब्ध नहीं है।',
      'saved': 'सहेजे गए',
      'no_saved': 'कोई सहेजा गया लेख नहीं है।',
      'check_out': 'यह लेख देखें: ',
      'unknown': 'अज्ञात',
      'explore': 'खोजें',
    },
    'mr': {
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'get_in_touch': 'संपर्क करा',
      'contact_desc': 'आमच्या बातम्यांबद्दल तुम्हाला काही प्रश्न, अभिप्राय किंवा चिंता असल्यास, कृपया खालील संपर्क माहिती वापरून आमच्याशी संपर्क साधा.',
      'website': 'वेबसाइट',
      'email': 'ईमेल',
      'follow_us': 'आम्हाला फॉलो करा',
      'home': 'होम',
      'bookmarks': 'बुकमार्क',
      'all': 'सर्व',
      'no_news': 'कोणत्याही बातम्या उपलब्ध नाहीत.',
      'unable_to_load': 'बातम्या लोड करण्यात अक्षम: ',
      'try_again': 'पुन्हा प्रयत्न करा',
      'search_hint': 'बातम्या शोधा...',
      'enter_search': 'शोधण्यासाठी शब्द प्रविष्ट करा',
      'no_results': 'कोणतेही परिणाम आढळले नाहीत.',
      'error': 'त्रुटी: ',
      'videos': 'व्हिडिओ',
      'no_videos': 'कोणतेही व्हिडिओ उपलब्ध नाहीत.',
      'no_news_category': 'या श्रेणीत कोणत्याही बातम्या उपलब्ध नाहीत.',
      'saved': 'सेव्ह केलेल्या बातम्या',
      'no_saved': 'तुम्ही अद्याप कोणत्याही बातम्या सेव्ह केलेल्या नाहीत.',
      'check_out': 'हा लेख पहा: ',
      'unknown': 'अज्ञात',
      'explore': 'शोधा',
    },
  };

  static String get(String lang, String key) {
    return _localizedStrings[lang]?[key] ?? _localizedStrings['en']![key]!;
  }
}
